language: python
python: 3.6

git:
  depth: 1

install:
  - pip3 install mkdocs mkdocs-material

branches:
  only:
    - master

before_deploy:
    - mkdocs build --verbose --clean

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs
    on:
      branch: master
