language: python

git:
  depth: 1

install:
  - pip install mkdocs mkdocs-material

script:
  - mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: sites
  on:
    branch: master
